### ISSUE TITLE
Installation date reported by Control Panel is sometimes off

### ISSUE THREAD

**Issue by joaomoreno** [Squirrel/Squirrel.Windows#374] opened 2015-06-25 08:23 UTC
We've had many [Code](https://code.visualstudio.com/) users report that its installation date reported by Control Panel is off. Sometimes in the past. Sometimes in the future.

I was skeptical until I saw it on my system: the installation date was sometime in April 2015, when I had actually installed the application this week. I uninstalled and installed it again and saw a date in the future: August 2015. Repeated it once more and now I can't reproduce anymore: installation date seems to always be accurate.

Any ideas?

**Comment by joaomoreno** [comment] 2015-06-25 09:42
Coincidentally, we've also had a number of complaints that uninstalling Code left Desktop shortcuts behind, similar to atom/atom#5901. Just as with the bug reported in this issue, I was very skeptical until I saw it: I did see it when I uninstalled Code while having the wrong Installation date, as per the story on the first comment. Of course, same as the date issue, I can't reproduce it anymore.

Maybe this extra information helps you get to the answer?

**Comment by paulcbetts** [comment] 2015-06-25 15:30
The problem is that the format of this regkey is super specific, and wasn't documented that it is locale-specific. It expects a different format for other countries but I have no idea what that format is

**Comment by paulcbetts** [comment] 2015-06-25 15:32
The uninstall shortcuts bug is unrelated, it means that either your hook is bailing sometimes, or there is a hidden bug in Squirrel, install logs would help

**Comment by Thieum** [comment] 2019-05-02 03:58
fixed in #616

**Closed** 2019-05-03 02:10 UTC
