### ISSUE TITLE
Trying to install Atom and I get an Error

### ISSUE THREAD

**Issue by michaeljcalkins** [Squirrel/Squirrel.Windows#192] opened 2015-01-15 22:56 UTC
Win 7 x64

```
Program: Starting Squirrel Updater: --install .
Program: Starting install, writing to C:\Users\Michael J. Calkins\AppData\Local\SquirrelTemp
CheckForUpdateImpl: Failed to load local releases, starting from scratch: System.IO.FileNotFoundException: Could not find file 'C:\Users\Michael J. Calkins\AppData\Local\atom\packages\RELEASES'.
File name: 'C:\Users\Michael J. Calkins\AppData\Local\atom\packages\RELEASES'
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at Squirrel.Utility.LoadLocalReleases(String localReleaseFile)
   at Squirrel.UpdateManager.CheckForUpdateImpl.<CheckForUpdate>d__28.MoveNext()
Utility: Starting to delete folder: C:\Users\Michael J. Calkins\AppData\Local\atom\packages
CheckForUpdateImpl: Reading RELEASES file from C:\Users\Michael J. Calkins\AppData\Local\SquirrelTemp
CheckForUpdateImpl: First run or local directory is corrupt, starting from scratch
ApplyReleasesImpl: Found partially applied release folder, killing it: C:\Users\Michael J. Calkins\AppData\Local\atom\app-0.174.0
Utility: Starting to delete folder: C:\Users\Michael J. Calkins\AppData\Local\atom\app-0.174.0
Utility: Starting to delete folder: C:\Users\Michael J. Calkins\AppData\Local\atom\app-0.174.0\locales
Utility: Starting to delete folder: C:\Users\Michael J. Calkins\AppData\Local\atom\app-0.174.0\resources
Utility: Starting to delete folder: C:\Users\Michael J. Calkins\AppData\Local\atom\app-0.174.0\resources\app
Utility: Starting to delete folder: C:\Users\Michael J. Calkins\AppData\Local\atom\app-0.174.0\resources\app\apm
Utility: Starting to delete folder: C:\Users\Michael J. Calkins\AppData\Local\atom\app-0.174.0\resources\app\apm\node_modules
Utility: Starting to delete folder: C:\Users\Michael J. Calkins\AppData\Local\atom\app-0.174.0\resources\app\apm\node_modules\.bin
Utility: Starting to delete folder: C:\Users\Michael J. Calkins\AppData\Local\atom\app-0.174.0\resources\app\apm\node_modules\atom-package-manager
Utility: Starting to delete folder: C:\Users\Michael J. Calkins\AppData\Local\atom\app-0.174.0\resources\app\apm\node_modules\atom-package-manager\bin
Utility: Starting to delete folder: C:\Users\Michael J. Calkins\AppData\Local\atom\app-0.174.0\resources\app\apm\node_modules\atom-package-manager\lib
Utility: Starting to delete folder: C:\Users\Michael J. Calkins\AppData\Local\atom\app-0.174.0\resources\app\apm\node_modules\atom-package-manager\native-module
Utility: Starting to delete folder: C:\Users\Michael J. Calkins\AppData\Local\atom\app-0.174.0\resources\app\apm\node_modules\atom-package-manager\native-module\src
Utility: Starting to delete folder: C:\Users\Michael J. Calkins\AppData\Local\atom\app-0.174.0\resources\app\apm\node_modules\atom-package-manager\node_modules
Utility: Starting to delete folder: C:\Users\Michael J. Calkins\AppData\Local\atom\app-0.174.0\resources\app\apm\node_modules\atom-package-manager\node_modules\.bin
Utility: Starting to delete folder: C:\Users\Michael J. Calkins\AppData\Local\atom\app-0.174.0\resources\app\apm\node_modules\atom-package-manager\node_modules\async
Utility: Starting to delete folder: C:\Users\Michael J. Calkins\AppData\Local\atom\app-0.174.0\resources\app\apm\node_modules\atom-package-manager\node_modules\async\lib
Utility: Starting to delete folder: C:\Users\Michael J. Calkins\AppData\Local\atom\app-0.174.0\resources\app\apm\node_modules\atom-package-manager\node_modules\colors
Utility: Starting to delete folder: C:\Users\Michael J. Calkins\AppData\Local\atom\app-0.174.0\resources\app\apm\node_modules\atom-package-manager\node_modules\colors\themes
Utility: Starting to delete folder: C:\Users\Michael J. Calkins\AppData\Local\atom\app-0.174.0\resources\app\apm\node_modules\atom-package-manager\node_modules\exit
Utility: Starting to delete folder: C:\Users\Michael J. Calkins\AppData\Local\atom\app-0.174.0\resources\app\apm\node_modules\atom-package-manager\node_modules\exit\lib
Utility: Starting to delete folder: C:\Users\Michael J. Calkins\AppData\Local\atom\app-0.174.0\resources\app\apm\node_modules\atom-package-manager\node_modules\first-mate
Utility: Starting to delete folder: C:\Users\Michael J. Calkins\AppData\Local\atom\app-0.174.0\resources\app\apm\node_modules\atom-package-manager\node_modules\first-mate\lib
Utility: Starting to delete folder: C:\Users\Michael J. Calkins\AppData\Local\atom\app-0.174.0\resources\app\apm\node_modules\atom-package-manager\node_modules\first-mate\node_modules
Utility: Starting to delete folder: C:\Users\Michael J. Calkins\AppData\Local\atom\app-0.174.0\resources\app\apm\node_modules\atom-package-manager\node_modules\first-mate\node_modules\emissary
Utility: Starting to delete folder: C:\Users\Michael J. Calkins\AppData\Local\atom\app-0.174.0\resources\app\apm\node_modules\atom-package-manager\node_modules\first-mate\node_modules\emissary\lib
Utility: Starting to delete folder: C:\Users\Michael J. Calkins\AppData\Local\atom\app-0.174.0\resources\app\apm\node_modules\atom-package-manager\node_modules\first-mate\node_modules\emissary\node_modules
Utility: Starting to delete folder: C:\Users\Michael J. Calkins\AppData\Local\atom\app-0.174.0\resources\app\apm\node_modules\atom-package-manager\node_modules\first-mate\node_modules\emissary\node_modules\harmony-collections
Utility: Starting to delete folder: C:\Users\Michael J. Calkins\AppData\Local\atom\app-0.174.0\resources\app\apm\node_modules\atom-package-manager\node_modules\first-mate\node_modules\emissary\node_modules\mixto
Utility: Starting to delete folder: C:\Users\Michael J. Calkins\AppData\Local\atom\app-0.174.0\resources\app\apm\node_modules\atom-package-manager\node_modules\first-mate\node_modules\emissary\node_modules\property-accessors
Utility: Starting to delete folder: C:\Users\Michael J. Calkins\AppData\Local\atom\app-0.174.0\resources\app\apm\node_modules\atom-package-manager\node_modules\first-mate\node_modules\emissary\node_modules\mixto\lib
Utility: Starting to delete folder: C:\Users\Michael J. Calkins\AppData\Local\atom\app-0.174.0\resources\app\apm\node_modules\atom-package-manager\node_modules\first-mate\node_modules\emissary\node_modules\property-accessors\lib
Utility: Starting to delete folder: C:\Users\Michael J. Calkins\AppData\Local\atom\app-0.174.0\resources\app\apm\node_modules\atom-package-manager\node_modules\first-mate\node_modules\emissary\node_modules\property-accessors\node_modules
Utility: Starting to delete folder: C:\Users\Michael J. Calkins\AppData\Local\atom\app-0.174.0\resources\app\apm\node_modules\atom-package-manager\node_modules\first-mate\node_modules\emissary\node_modules\property-accessors\node_modules\harmony-collections
ApplyReleasesImpl: Writing files to app directory: C:\Users\Michael J. Calkins\AppData\Local\atom\app-0.174.0
IEnableLogger: Failed to write file: C:\Users\Michael J. Calkins\AppData\Local\atom\app-0.174.0: System.IO.PathTooLongException: The specified path, file name, or both are too long. The fully qualified file name must be less than 260 characters, and the directory name must be less than 248 characters.
   at System.IO.PathHelper.GetFullPathName()
   at System.IO.Path.NormalizePath(String path, Boolean fullCheck, Int32 maxPathLength, Boolean expandShortPaths)
   at System.IO.Path.NormalizePath(String path, Boolean fullCheck, Int32 maxPathLength)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at NuGet.PhysicalPackageFile.GetStream()
   at Squirrel.UpdateManager.ApplyReleasesImpl.<>c__DisplayClass8b.<copyFileToLocation>b__8a()
   at Squirrel.Utility.LogIfThrows(IFullLogger This, LogLevel level, String message, Action block)
IEnableLogger: Failed to install package to app dir: System.IO.PathTooLongException: The specified path, file name, or both are too long. The fully qualified file name must be less than 260 characters, and the directory name must be less than 248 characters.
   at System.IO.PathHelper.GetFullPathName()
   at System.IO.Path.NormalizePath(String path, Boolean fullCheck, Int32 maxPathLength, Boolean expandShortPaths)
   at System.IO.Path.NormalizePath(String path, Boolean fullCheck, Int32 maxPathLength)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at NuGet.PhysicalPackageFile.GetStream()
   at Squirrel.UpdateManager.ApplyReleasesImpl.<>c__DisplayClass8b.<copyFileToLocation>b__8a()
   at Squirrel.Utility.LogIfThrows(IFullLogger This, LogLevel level, String message, Action block)
   at Squirrel.UpdateManager.ApplyReleasesImpl.copyFileToLocation(FileSystemInfo target, IPackageFile x)
   at Squirrel.UpdateManager.ApplyReleasesImpl.<>c__DisplayClass84.<installPackageToAppDir>b__80(IPackageFile x)
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at Squirrel.UpdateManager.ApplyReleasesImpl.<>c__DisplayClass84.<installPackageToAppDir>b__7f()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.UpdateManager.ApplyReleasesImpl.<installPackageToAppDir>d__86.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.Utility.<LogIfThrows>d__4b`1.MoveNext()
```

**Comment by paulcbetts** [comment] 2015-01-15 23:01
There's not much Squirrel can do here, this is a "Paths too long" bug in Atom :(   It's not a good solution, but you _could_ download https://github.com/atom/atom/releases/download/v0.174.0/atom-windows.zip and put it in `C:\Atom`

**Comment by bryankaraffa** [comment] 2015-01-15 23:08
I am receiving this error as well too.  Perhaps there could be a flag or way to specify the install directory?

**Comment by paulcbetts** [comment] 2015-01-15 23:09
@bryankaraffa Atom just needs to fix the long paths, no need to set flags

**Comment by bryankaraffa** [comment] 2015-01-15 23:10
@paulcbetts Makes sense to me! :+1:

**Comment by lodotek** [comment] 2015-01-16 23:43
Yep same issue here...

**Comment by vncastanheira** [comment] 2015-01-19 15:40
Had this issue today.

**Comment by paulcbetts** [comment] 2015-01-19 18:44
I'm gonna close this out because we can't do anything much about it

**Closed by paulcbetts** 2015-01-19 18:44 UTC

**Comment by dc-afinnell** [comment] 2015-02-13 23:18
It seems there is quite a bit that can be done about this problem. Out of a 260 character limit Atom uses 85% of those characters. That leads me to believe the problem is with Atom not a person's Username or any such thing. The names of the directories underneath the Atom install are ridiculously long.

**Comment by paulcbetts** [comment] 2015-02-13 23:19
@dc-afinnell When I say "we can't do anything about it", I mean "we" as in Squirrel. Atom can certainly do something about it.

**Comment by dc-afinnell** [comment] 2015-02-13 23:21
@paulcbetts I will humbly eat that pie.. I didn't see which project I was in before speaking. My apologies.

**Comment by paulcbetts** [comment] 2015-02-13 23:22
@dc-afinnell No worries :)
