### ISSUE TITLE
How can the user move to a previous version?

### ISSUE THREAD

**Issue by SissiKonsta** [Squirrel/Squirrel.Windows#796] opened 2016-08-12 09:56 UTC
Hello,

Is it possible to give the user the ability to move to a previous version?

Thank you in advance.

**Comment by kneuvirth** [comment] 2016-09-06 19:17
I have been trying to do this same thing. Any help would be appreciated.

**Comment by andymartinwork** [comment] 2016-09-08 12:14
Have them uninstall the current version, and send them the installer for the old version?

**Comment by gojanpaolo** [comment] 2019-05-06 18:03
@shiftkey duplicate of other rollback issues (#524, #964)

**Comment by Thieum** [comment] 2019-05-06 19:16
@shiftkey @gojanpaolo the "original" downgrade issue is #145 Should we consolidate?

**Comment by gojanpaolo** [comment] 2019-05-06 19:33
@Thieum yes. I think we should update the documentation and then close the two I mentioned above as those discusses the workarounds/strategies instead of having it built-in the library.

**Comment by shiftkey** [comment] 2019-05-12 14:35
Closing this out in favour of #524

**Closed by shiftkey** 2019-05-12 14:35 UTC
