### ISSUE TITLE
UpdateManager.RestartApp() does not work if we have spaces in the name of the .exe

### ISSUE THREAD

**Issue by SissiKonsta** [Squirrel/Squirrel.Windows#1165] opened 2017-10-02 20:49 UTC
Hello,

I want to have an executable with spaces, for example  " **My Application.exe** ", and use Squirrel for the update process. Squirrel checks and downloads updates, if any, correctly but when it comes to restarting the application using UpdateManager.RestartApp(), it crashes. I have created an example project where the executable does not have spaces and another one with the same code but with spaces in its executable. The first one works as it should but the second one crashes. Why is this happening? Does anyone have any idea? Did anyone else have this issue? 

Thank you in advance.

Sissi Konsta

**Comment by paulcbetts** [comment] 2017-10-02 20:52
This is probably a bug, can you send in a PR to fix it?

**Comment by SissiKonsta** [comment] 2017-10-03 16:03
@paulcbetts I have created a pull request for this issue.

**Comment by SissiKonsta** [comment] 2017-10-10 12:04
Hello.

@paulcbetts is there any update regarding PR #1166?

**Comment by Thieum** [comment] 2019-05-03 14:14
@shiftkey duplicate of #713, this can be closed.

**Closed** 2019-05-04 21:07 UTC
