### ISSUE TITLE
Multiple exe package

### ISSUE THREAD

**Issue by genyx** [Squirrel/Squirrel.Windows#1241] opened 2018-01-26 10:12 UTC
I have a project that includes a `ChromiumFXRenderProcess.exe` coming from a nuget package, and i can not change it.

I included Squirrel with custom events in my application. The shortcut for my main program gets done all fine. The Squirrel installer starts all the exe files in the package at install-time (i guess to determine, which one is an actual Squirrel-Aware App). 
But the problem is: on some Windows 7 machines, there pops up an error message mid installation saying "ChromiumFXRenderProcess.exe has stopped working". Well, because ChromiumFXRenderProcess.exe is not supposed to start "standalone".

Is there a way to define in the Squirrel setup.exe which one could actually be a Squirrel-Aware-App or which to exclude?

**Comment by Slion** [comment] 2018-01-26 13:40
Did you set the following in your main EXE AssemblyInfo.cs?
`[assembly: AssemblyMetadata("SquirrelAwareVersion", "1")]`

**Comment by Thieum** [comment] 2019-05-01 13:32
duplicate of #999

**Closed** 2019-05-01 13:36 UTC
