### ISSUE TITLE
Attempt to read or write Protected Memory This is often an indicating that other memory is corrupt

### ISSUE THREAD

**Issue by zetalpha** [Squirrel/Squirrel.Windows#1798] opened 2022-03-30 11:06 UTC
the SetPreference in the PromoteTrayItem() method will report an error

[Attempt to read or write Protected Memory This is often an indicating that other memory is corrupt]

**Comment by robmen** [comment] 2022-06-01 06:45
Duplicate of #1659

**Closed by robmen** 2022-06-01 06:45 UTC
