### ISSUE TITLE
Update issue when executable name contains spaces

### ISSUE THREAD

**Issue by MahdiGhiasi** [Squirrel/Squirrel.Windows#1122] opened 2017-08-05 13:32 UTC
I call `UpdateManager.RestartApp();` after calling `await mgr.UpdateApp();`, so my app restarts automatically after update. However, it fails to restart the app if the executable name contains spaces.

Based on update log, it seems that it only takes the first part of name (until the first space). So if executable name is `My Amazing App.exe`, it'll try to run `%localappdata%\myapp\app-1.0.4\My`, and obviously it fails to do so.

**Comment by shiftkey** [comment] 2017-08-06 03:43
@mghiasi75 could you attach the bits from the log where this is being called (and failing)? Also, information about which version of Squirrel you're using will help to troubleshoot...

**Comment by Thieum** [comment] 2019-05-03 14:13
@shiftkey duplicate of #713, this can be closed.

**Closed** 2019-05-04 21:06 UTC
