### ISSUE TITLE
Compatibility with new major version of DeltaCompressionDotNet

### ISSUE THREAD

**Issue by Amoenus** [Squirrel/Squirrel.Windows#1325] opened 2018-05-29 14:06 UTC
The new major version of **DeltaCompressionDotNet** has been released (2.0.0).
The current version of **squirrel.windows** (1.8.0) is not compatible with it due to constraint (>=1.1.0 && < 2.0.0).

**Comment by chatzisa** [comment] 2018-05-29 14:12
Will be great to have that issue sorted soon, thanks.

**Comment by paulcbetts** [comment] 2018-05-29 16:20
What benefits are there to upgrading?

**Comment by yarseyah** [comment] 2019-03-09 14:56
@paulcbetts mainly for me, it stops me from using 2.0.0 of DeltaCompressionDotNet within a solution that includes the auto-update functionality of squirrel.windows and tops me from having a build process that doesn't keep flagging up that an upgrade of packages are available.

**Comment by Thieum** [comment] 2019-05-01 12:34
duplicate of #1181

**Closed** 2019-05-01 12:39 UTC
