### ISSUE TITLE
Question: Is it possible to pass command line arguments to an up via Squirrel's update.exe

### ISSUE THREAD

**Issue by veleek** [Squirrel/Squirrel.Windows#802] opened 2016-08-22 04:23 UTC
I have an app that I would like to launch using a command line argument, and as #736 I want to be able to open the most recent version of the app by using `update.exe`.

Can command line arguments be passed through to the app?  The help for `update.exe` doesn't reference `--processStart` anywhere so I'm not sure.

**Comment by KirillOsenkov** [comment] 2016-08-22 17:57
Apparently there is processStartArgs:
https://github.com/Squirrel/Squirrel.Windows/blob/ee32fb469fc1ace0af6aef7edc389e27b8c063bb/src/Update/Program.cs#L93

**Comment by Thieum** [comment] 2019-05-07 16:19
@shiftkey duplicate of #483, this can be closed.

**Closed** 2019-05-09 11:30 UTC
