### ISSUE TITLE
Installation in Program Files or Program Files (x86) folder

### ISSUE THREAD

**Issue by Neustradamus** [Squirrel/Squirrel.Windows#1608] opened 2020-04-03 20:39 UTC
Can you add the feature to have the possibility to install in:
- Program Files
- Program Files (x86)

The best missing feature of the World.

Thanks in advance.

**Comment by anaisbetts** [comment] 2020-04-07 02:09
Dupe of #382

**Closed by anaisbetts** 2020-04-07 02:09 UTC
