### ISSUE TITLE
Update to pre-release version failure

### ISSUE THREAD

**Issue by rmcshane** [Squirrel/Squirrel.Windows#757] opened 2016-07-01 19:21 UTC
I have an Electron application with pre-release builds version in the format
`1.2.3-build.1`

While using the grunt-electron-installer I'm getting output build files
`myapp-0.0.1-build1-full.nupkg`
`myapp-0.0.1-build1-delta.nupkg`
(For some reason Squirrel is stripping the period in "build.1" but that's not a big deal.)

The issue is when the pre-release builds go from build.9 to build.10, the update process fails.  The updater does not find any updates even though they're available.

**Comment by paulcbetts** [comment] 2016-07-01 19:21
This probably isn't supported, sorry :-/

**Comment by gojanpaolo** [comment] 2019-05-06 18:06
@shiftkey duplicate of supporting semver2 (#1394)

**Comment by shiftkey** [comment] 2019-05-06 23:54
@gojanpaolo yep, this is probably related to Semver2 support

**Closed by shiftkey** 2019-05-06 23:54 UTC
