### ISSUE TITLE
Skipping versions

### ISSUE THREAD

**Issue by SissiKonsta** [Squirrel/Squirrel.Windows#1419] opened 2018-11-19 20:57 UTC
Hello,

Is there any way we can go from version 10 to version 20 directly without going from 10 to 11, 11 to 12, 12 to 13, etc?

Thanks.

Sissi Konsta

**Comment by bddckr** [comment] 2018-11-20 06:41
> [...] if there is a new release, the UpdateManager determines whether to download the deltas or the latest full package (by calculating which one requires less total downloading) to update to the current version. [...]
https://github.com/Squirrel/Squirrel.Windows/blob/master/docs/using/update-process.md

**Comment by Thieum** [comment] 2019-05-02 04:17
@shiftkey can be closed as by design.

**Closed** 2019-05-02 11:32 UTC
