### ISSUE TITLE
Install screen at small size and cannot be moved

### ISSUE THREAD

**Issue by thepeanutman98** [Squirrel/Squirrel.Windows#1161] opened 2017-09-28 22:04 UTC
This is the image of my screen.
![image](https://user-images.githubusercontent.com/22580382/30755973-8b86ad58-9f96-11e7-8dbb-c5e9ef9570d3.png)
It is on a secondary screen (not primary) with resolution 1680x1050.
It should be able to be moved, but it can't, and the window shows at about 1/2 size.

I posted this as atom/atom#15724 on the Atom repo, but a maintainer said it should be reported upstream here.

**Comment by vadi2** [comment] 2017-11-09 09:50
Duplicate of https://github.com/Squirrel/Squirrel.Windows/issues/1124

**Comment by damieng** [comment] 2018-01-03 20:43
Caused by https://github.com/Squirrel/Squirrel.Windows/pull/1061

**Comment by Thieum** [comment] 2019-05-03 03:42
@shiftkey duplicate of #1124, fixed by #1233 , this can be closed.

**Closed** 2019-05-03 12:55 UTC
