### ISSUE TITLE
Need proper formatting for HTTP URL content (add to documentation?)

### ISSUE THREAD

**Issue by InteXX** [Squirrel/Squirrel.Windows#1219] opened 2017-12-24 11:38 UTC
I'm trying to find out what I need to return to `Squirrel.UpdateManager` from my IIS application, in order to apply updates.

Below is my current .ASHX code. This is producing an error _'Invalid release entry: MyApp-1.0.0-full.nupkg'_ that I'm not able to get past.

What does Squirrel expect to see from my HTTP URL?

--------------------------------------------------------

    Sub ProcessRequest(Context As HttpContext) Implements IHttpHandler.ProcessRequest
      Dim oFolder As DirectoryInfo
      Dim oFiles As List(Of FileInfo)

      Context.Response.ContentType = "text/plain"

      oFolder = New DirectoryInfo(Context.Server.MapPath("~"))
      oFiles = oFolder.GetFiles("*.nupkg").ToList
      oFiles.AddRange(oFolder.GetFiles("Setup.*"))
      oFiles.AddRange(oFolder.GetFiles("RELEASES"))

      oFiles.ForEach(Sub(F)
                       Context.Response.Write(F.Name & vbCrLf)
                     End Sub)
    End Sub

The output looks like this:

> MyApp-1.0.0-full.nupkg
MyApp-1.0.1-delta.nupkg
MyApp-1.0.1-full.nupkg
MyApp-1.0.2-delta.nupkg
MyApp-1.0.2-full.nupkg
MyApp-1.0.3-delta.nupkg
MyApp-1.0.3-full.nupkg
Setup.exe
Setup.msi
RELEASES

**Comment by Thieum** [comment] 2019-05-03 03:25
@shiftkey duplicate of #744 , this can be closed.

**Closed** 2019-05-03 07:31 UTC
