### ISSUE TITLE
Administrator Deffined Default Install Path

### ISSUE THREAD

**Issue by tarius007** [Squirrel/Squirrel.Windows#1841] opened 2023-01-11 10:24 UTC
Our company have Windows Server witch is used as RDP server.
Our policy disallows executing any program from %AppData% witch prevents "Teams" Microsoft application that
use your installer to running properly. Many Viruses and Ransomware use this location for storing its payload. Therefore we must
block it.

Please add option for storing installed application in administrator defined location. (on global level not per-user level)
(Can be registry setting in HKLM for example ,or local config file witch define base location)

Example : C: \ SquirellAppsRepo \ <user_name> \ <package_name>

This way admin can set base install dir to any directory while user has its own specific instalation under this directory.

Setting default location to %AppData% is extremly unfriendly in busines enviroment !

**Comment by anaisbetts** [comment] 2023-01-11 10:41
Dupe of #1002

**Closed as completed by anaisbetts** 2023-01-11 10:41 UTC
