### ISSUE TITLE
Setup.exe crashes when handling events with SquirrelAwareApp and using hyphen in version

### ISSUE THREAD

**Issue by daveaglick** [Squirrel/Squirrel.Windows#688] opened 2016-05-10 21:49 UTC
NuGet supports semver, including the optional use of a hyphen at the end of a version to indicate pre-release (or other build related info). This appears to crash Squirrel during event handling if using `SquirrelAwareApp`. The memory dump indicates the failure is at https://github.com/Squirrel/Squirrel.Windows/blob/master/src/Squirrel/SquirrelAwareApp.cs#L67 with

```
An unhandled exception of type 'System.FormatException' occurred in mscorlib.dll
Additional information: Input string was not in a correct format.
```

I see two current workarounds:
- Strip the build/pre-release information from the NuGet package used for Squirrel
- Handle the events without using `SquirrelAwareApp`

Out of curiosity, why bother creating a `Version` object at all? It doesn't appear to be needed by the `SquirrelAwareApp` class so it should be possible to pass a version string back in the event instead and leave it up to the handler of the event to create a `Version` instance if needed.

**Comment by jochenvangasse** [comment] 2016-06-07 09:57
Seems like a got the same issue

Bit curious indeed that it uses the standard Version class from .Net, when Nuget semver does support prerelease tagging

**Comment by gojanpaolo** [comment] 2019-05-06 18:18
@shiftkey duplicate of #1394

**Closed** 2019-05-06 23:56 UTC
