### ISSUE TITLE
Add exit codes to update.exe

### ISSUE THREAD

**Issue by GeertvanHorrik** [Squirrel/Squirrel.Windows#1320] opened 2018-05-17 07:33 UTC
Sometimes you want to run Squirrel outside the context of the manager. Then exit codes can give great insights in what happened while executing the update.exe.

My proposal:

```
    public static class ExitCodes
    {
        // Possible exit codes:
        // -1 => An error occurred. Check the log file for more information about this error
        //  0 => No errors, no additional information available
        //  1 => New version available or new version is installed successfully (depending on switch /checkonly)
        //  2 => New version which is mandatory (forced) is available (for the future?)
        //  3 => No new version available

        public const int ErrorOccurred = -1;
        public const int NothingToReport = 0;
        public const int NewVersionInstalled = 1;
        public const int NewMandatoryVersionInstalled = 2;
        public const int NoNewVersionAvailable = 3;
    }
```

Happy to PR.

**Comment by Thieum** [comment] 2019-05-01 13:53
duplicate of #98

**Closed** 2019-05-01 13:54 UTC
