### ISSUE TITLE
Squirrel replaces spaces in filename with %20

### ISSUE THREAD

**Issue by Deozaan** [Squirrel/Squirrel.Windows#544] opened 2016-01-06 08:56 UTC
A dependency I have no control over has spaces in one of the filenames. The NuGet Package manager translates the spaces to %20 in the nuget package. After releasifying the package in Squirrel and using Setup.exe to install, things are broken because the file that should have spaces in its name has %20 in there instead.

I tried editing the package file to change the %20 to spaces, but that just broke things earlier in the process (Squirrel wouldn't even package it up into a setup.exe file).

To be clearer: It is NuGet's fault that the spaces get turned into %20 when creating the package. But Squirrel should be smart enough to convert the %20 to a space when it is unpacking/creating the files.

**Comment by geary** [comment] 2016-01-18 22:35
I've run into this too. Any Unity app will have this problem because of this file: `appname_Data\Resources\unity default resources`

I wonder if this just affects spaces or other "escapable" characters too?

Looking through the Squirrel code, the one bit of code that seems related is the `Uri.EscapeUriString()` call in `compressFolderEncoded()` and the `Uri.UnescapeDataString()` call in `extractZipDecoded()` (both in `src\Squirrel\ReleasePackage.cs`).

At first it seemed obvious that these were matched up properly, but if NuGet is doing *another* escape that would be a different story. Maybe Squirrel needs to do another unescape, or not do this escape?

In the meantime, since it's just that one file breaking my app, I worked around it by adding this bit of code to my launcher app (a "Squirrel aware" app that runs before the Unity app):

    static void FixupFiles() {
        FixupSpaces(
            Path.Combine( DataDir, "Resources" ),
            "unity default resources"
        );
    }

    static void FixupSpaces( string dir, string file ) {
        var newFile = Path.Combine( dir, file );
        var oldFile = Path.Combine( dir, file.Replace( " ", "%20" ) );
        if( File.Exists( oldFile ) ) {
            File.Delete( newFile );
            File.Move( oldFile, newFile );
        }
    }

And then I call `FixupFiles()` in the `onInitialInstall` and `onAppUpdate` events.

`DataDir` is a static property with the name of the Unity data directory, e.g. `MyAppMain_Data`. Adjust as needed for a non-Unity app.

**Comment by Deozaan** [comment] 2016-01-18 23:58
Yeah, Unity is the dependency I mentioned. Thanks for posting the workaround.

That said, I hope Squirrel fixes this soon.

**Comment by Ran-Intendu** [comment] 2016-02-07 15:55
Duplicates #414

**Comment by Thieum** [comment] 2019-05-03 14:08
@shiftkey duplicate of #414, this can be closed in favor of the previous issue.

**Closed** 2019-05-04 21:07 UTC
