### ISSUE TITLE
Unhandled exception: System.IO.IOException: The process cannot access the file 'xxx.nupkg' because it is being used by another process

### ISSUE THREAD

**Issue by jmelosegui** [Squirrel/Squirrel.Windows#422] opened 2015-08-30 21:42 UTC
Hi 

I am trying to use squirrel for windows and there is no way to get rid of that error.

I have done everything to be sure that that file is indeed not in use.

 1. restart the pc
 2. open command prompt only (no other application is running, not even visual studio)
 3. Run the command ```squirrel --releasify Digger.1.0.0.1.nupkg```

Those steps reproduce the error on my pc. The weird thing is that I am be able to delete the file right after getting the error from the releasify command:

The following is the log. Any help???

```
2015-08-30 17:28:03> Program: Starting Squirrel Updater: --releasify Digger.1.0.0.1.nupkg
2015-08-30 17:28:03> Program: Bootstrapper EXE found at:C:\dev\utils\squirrel\Setup.exe
2015-08-30 17:28:03> Program: Creating release package: C:\dev\projects\ThirdParty\inmediati\Digger\Digger.Cliente.WPF\Releases\Digger.1.0.0.1.nupkg
2015-08-30 17:28:03> ReleasePackage: Creating release package: C:\dev\projects\ThirdParty\inmediati\Digger\Digger.Cliente.WPF\Releases\Digger.1.0.0.1.nupkg => C:\dev\projects\ThirdParty\inmediati\Digger\Digger.Cliente.WPF\Releases\Digger-1.0.0.1-full.nupkg
2015-08-30 17:28:03> ReleasePackage: Extracting dependent packages: []
2015-08-30 17:28:03> ReleasePackage: Removing unnecessary data
2015-08-30 17:28:03> ReleasePackage: No release notes found in C:\Users\Juan\AppData\Local\SquirrelTemp\tempa\Digger.nuspec
2015-08-30 17:28:03> Unhandled exception: System.IO.IOException: The process cannot access the file 'C:\dev\projects\ThirdParty\inmediati\Digger\Digger.Cliente.WPF\Releases\Digger.1.0.0.1.nupkg' because it is being used by another process.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalDelete(String path, Boolean checkHost)
   at System.IO.File.Delete(String path)
   at Squirrel.Update.Program.Releasify(String package, String targetDir, String packagesDir, String bootstrapperExe, String backgroundGif, String signingOpts, String baseUrl, String setupIcon)
   at Squirrel.Update.Program.executeCommandLine(String[] args)
   at Squirrel.Update.Program.main(String[] args)
```

Thanks in advance.

**Comment by SamyPesse** [comment] 2015-08-31 07:05
I had the same error on AppVeyor when building our application, but only for x64 builds (x86 were working perfectly).

**Comment by jmelosegui** [comment] 2015-08-31 12:25
Hi @SamyPesse 

Thanks for your response. Does that means I need to explicitly set the build configuration to x86? (My current configuration is Any CPU)

**Comment by janpieterz** [comment] 2015-08-31 15:04
I have the same problem! Unable to find any specifics so far.

**Comment by dspickes** [comment] 2015-08-31 16:07
This is happening for me as well with Any CPU as my build configuration and the same stack trace. Reverting Squirrel to 0.99.2 also fixed it, but isn't an ideal solution.

**Comment by janpieterz** [comment] 2015-08-31 16:37
I've found the bug and the solution. In the ReleasePackage.cs file the new method extractZipDecoded doesn't close the ZipFile it creates, which keeps a filestream open.

**Comment by gruebait** [comment] 2015-09-02 23:55
> Reverting Squirrel to 0.99.2 also fixed it, but isn't an ideal solution.

Another solution is to stop using Squirrel altogether until it stabilizes a bit more.

**Comment by paulcbetts** [comment] 2015-09-04 21:33
This should be fixed in #425, please reopen if this bug shows up again!

**Closed by paulcbetts** 2015-09-04 21:33 UTC

**Comment by VTopoliuk** [comment] 2016-09-27 12:47
I have exactly the same problem.
Squirrel.windows Version 1.4.4
Windows 8.1 
Visual Studio 2013

**Comment by ChristopheCuddlup** [comment] 2016-10-19 15:12
Hi,

I got the same error. Took me some time to understand the reason. 
You can reproduce this issue if you generate with the Nuget Package Explorer, a .nupkg file directly in the Releases folder (below the .sln folder).
Then, running the Squirrel --releasify command leads to the same exception.
Fix is simply to move the source .nupkg file to another folder, but it would be great if the Squirrel command could tell the developer to do so.
BTW, I am running Version 1.4.4.
Thanks for the great job!

**Comment by UnnecessaryPunctuation** [comment] 2022-06-07 13:14
I have the same issue on 2.0.1 :

\packages\squirrel.windows.2.0.1\tools\

[07/06/22 14:58:22] fatal: Finished with unhandled exception: System.IO.IOException: Le processus ne peut pas accÃ©der au fichier 'XYZ\bin\Debug\DevDebug.1.0.1.nupkg', car il est en cours d'utilisation par un autre processus.
   Ã  System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   Ã  System.IO.File.InternalCopy(String sourceFileName, String destFileName, Boolean overwrite, Boolean checkHost)
   Ã  Squirrel.Update.Program.Releasify(String package, String targetDir, String packagesDir, String bootstrapperExe, String backgroundGif, String signingOpts, String baseUrl, String setupIcon, Boolean generateMsi, Boolean packageAs64Bit, String frameworkVersion, Boolean generateDeltas)
   Ã  Squirrel.Update.Program.executeCommandLine(String[] args)
   Ã  Squirrel.Update.Program.main(String[] args)
