### ISSUE TITLE
Uninstaller issues

### ISSUE THREAD

**Issue by vaneshqa** [Squirrel/Squirrel.Windows#1209] opened 2017-11-22 11:37 UTC
Our test case:
1. There are two users in machine. First user (USER_A) with admin rights, second is standard user without admin rights (USER_B).
2. Under each user I'm installing application. That works fine, application files copied to "%username%\AppData\Local\AppName" folder, shortcuts created in Desktop and Start menu.
3. Then I am trying to remove program under standard user which has no admin rights (USER_B) using Control panel -> Programs and features. The problems goes there. When I clicking "Uninstall" UAC is asking me to grant admin privileges. Since current user (USER_B) has no admin privileges, I am selecting another account which has admin privileges (USER_A). Please notice that application is installed in this account too. As a result of these actions I have following state:
- Application files removed from USER_B\AppData\Local\AppName - OK
- Shortcuts removed for USER_A, not for current user (USER_B). So after removing application in USER_B account I still see shortcuts in desktop and start menu, but they disappeared for USER_A.
- Same situation with uninstaller register entry (Software/Microsoft/Windows/CurrentVersion/Uninstall). It is removed for USER_A, but still exists for USER_B.

You could see below our code which handles shortcuts.

````
SquirrelAwareApp.HandleEvents(
                        onInitialInstall: version =>
                        {
                            mgr.CreateShortcutForThisExe();
                        },
                        onAppUpdate: version =>
                        {
                        },
                        onAppUninstall: version =>
                        {
                            //-squirrel-uninstall
                            mgr.RemoveShortcutForThisExe();
                        },
                        onFirstRun: () =>
                        {
                            //--squirrel-firstrun
                        }
                    );
````

**Comment by mrlambouk** [comment] 2018-10-05 11:16
Are there any updates on this? I am seeing the exact behavior in our QA testing.

**Comment by paulcbetts** [comment] 2018-10-05 15:05
The uninstaller doesn't need elevation, why is Windows elevating it anyways?

**Comment by mrlambouk** [comment] 2018-10-08 15:57
Update: We can reliably reproduce this when we Uninstall our app from Apps & Features. We cannot reproduce this issue if we Uninstall via "Control Panel\Programs\Programs and Features" on a non-admin user account.

We are using version 1.78 of Squirrel.Windows. Can you confirm if this issue is fixed in the latest version?

**Comment by paulcbetts** [comment] 2018-10-08 17:04
@mrlambouk It is not changed in the latest version. This sounds like a Windows bug where Apps and Features is blindly elevating everything. Can you file this with Microsoft as a Feedback item?

**Comment by mrlambouk** [comment] 2018-10-09 10:15
I have tested with the latest version of Squirrel.Windows (version 1.9.0) and unfortunately the issue is still reproducible.

To confirm environment: Windows 10 - Version 1803 (OS Build 17134.285)

This only occurs when Uninstalling from "Apps & Features". It works fine from "Control Panel >> Programs and Features"

**Comment by mrlambouk** [comment] 2018-10-09 10:17
@paulcbetts Sure, I'll see about raising this with M$. Thanks.

**Comment by Robbos** [comment] 2018-12-07 11:08
@mrlambouk do you have a link to your issue with Microsoft? I would also like to get this resolved.

**Comment by mrlambouk** [comment] 2018-12-07 21:07
@robbos we didn't raise a ticket in the end and have instead altered our documentation.

**Comment by Thieum** [comment] 2019-05-03 14:34
@shiftkey seems like it's (was?) a windows bug, this can be closed.

**Comment by shiftkey** [comment] 2019-05-04 21:16
Closing this out as external to Squirrel.Windows, and I believe not something we can address directly in the project.

**Closed by shiftkey** 2019-05-04 21:16 UTC
