### ISSUE TITLE
Replace SharpZipLib with ZipArchive/ZipFile

### ISSUE THREAD

**Issue by davkean** [Squirrel/Squirrel.Windows#220] opened 2015-02-09 08:08 UTC
I see that Squirrel.Windows now requires .NET Framework 4.5 as a minimum, in which case, you can remove the usage of SharpZipLib (which I must admit, kind of scares me with their _GPL but not GPL when a library_ license) with [ZipArchive](https://msdn.microsoft.com/en-us/library/system.io.compression.ziparchive.aspx)/[ZipFile](https://msdn.microsoft.com/en-us/library/system.io.compression.zipfile.aspx).

**Comment by paulcbetts** [comment] 2015-02-09 08:13
If you submit a PR and it works I'll take it, but the last time I tried to do this, tons of Bad Things happened to me (I can't recall the details though)

**Comment by eeevans** [comment] 2015-05-04 18:44
Just switching these out, I go from 10 test failures to 19.  The error on the extra 9 are System.InvalidOperationException Package does not contain a manifest.  Haven't figured out what the issue is yet.  Still looking.

**Comment by Thieum** [comment] 2019-04-30 17:39
SharpZipLib has been replaced by SharpCompress in #803 
Not sure if switching to ZipArchive/ZipFile is still relevant / needed, considering the original main concern was the licensing.

**Comment by shiftkey** [comment] 2019-04-30 17:41
I'm going to close this out because I don't think we're planning to change out such an important piece of the project in the short term.

**Closed by shiftkey** 2019-04-30 17:41 UTC
Labels: infrastructure
