### ISSUE TITLE
Gitter or Discord chat channel ?

### ISSUE THREAD

**Issue by donnib** [Squirrel/Squirrel.Windows#1271] opened 2018-03-13 11:37 UTC
@paulcbetts have you considered above ? I think it would be a great idea to have a place for support/discussion no ?

**Comment by Logikgate** [comment] 2018-03-15 13:37
There's already a Slack channel for Squirrel, the below link has information on joining

https://github.com/Squirrel/Squirrel.Windows/blob/master/docs/contributing/contributing.md

**Comment by donnib** [comment] 2018-03-15 14:52
@Logikgate yes but that's not what i am after. I want a place for support / discussion and not for contributing which is the case with the Slack channel.

**Comment by jacksonisiah** [comment] 2018-04-03 16:43
wouldn't doubt that you could get help in that slack channel. 

don't feel the need for anything else.

**Comment by Thieum** [comment] 2019-05-01 12:51
duplicate of #9

**Closed** 2019-05-01 12:51 UTC
