### ISSUE TITLE
Support to .NET framework 4.6.1.

### ISSUE THREAD

**Issue by ManpreetSingh24** [Squirrel/Squirrel.Windows#597] opened 2016-02-10 15:30 UTC
Squirrel --releasify, supports max framework as 4.5. 
I target my application to .NET 4.6.1.

Squirrel.com : System.InvalidOperationException: The input package file D:\Mainstream\Project\LIO-DataDesktopPortal\trunk\LIO-DataDesktopPortal\LIO-Data
Portal.Client\Releases\Liodata_Portal.13.75.0.0.nupkg targets multiple platforms - .NETFramework,Version=v4.5.1; .NETFramework,Version=v4.6.1;  - and ca
nnot be transformed into a release package.
At line:1 char:9
+ Squirrel <<<<  --releasify .\Liodata_Portal.13.75.0.0.nupkg
    + CategoryInfo          : NotSpecified: (System.InvalidO...elease package.:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
   at Squirrel.ReleasePackage.CreateReleasePackage(String outputFile, String packagesRootDir, Func`2 releaseNotesProcessor, Action`1 contentsPostProcess
Hook)
   at Squirrel.Update.Program.Releasify(String package, String targetDir, String packagesDir, String bootstrapperExe, String backgroundGif, String signi
ngOpts, String baseUrl, String setupIcon, Boolean generateMsi)
   at Squirrel.Update.Program.executeCommandLine(String[] args)
   at Squirrel.Update.Program.main(String[] args)
   at Squirrel.Update.Program.Main(String[] args)

**Comment by paulcbetts** [comment] 2016-02-10 16:12
Dupe of #188, please go subscribe there

**Closed by paulcbetts** 2016-02-10 16:12 UTC
