### ISSUE TITLE
entryRegex throws Exception and update fails when filename contains spaces

### ISSUE THREAD

**Issue by albay** [Squirrel/Squirrel.Windows#1420] opened 2018-11-21 11:49 UTC
### Version: 1.8.0

System.Exception: Invalid release entry: 6D2F891EACAA7B811011F09B27BAAE242C807447 Not Secure Cookie.txt.shasum 685
   at Squirrel.ReleaseEntry.ParseReleaseEntry(String entry)
   at Squirrel.DeltaPackageBuilder.verifyPatchedFile(String relativeFilePath, String inputFile, String tempTargetFile)
   at Squirrel.DeltaPackageBuilder.applyDiffToFile(String deltaPath, String relativeFilePath, String workingDirectory)
   at Squirrel.EnumerableExtensions.ForEach[TSource](IEnumerable`1 source, Action`1 onNext)
   at Squirrel.DeltaPackageBuilder.ApplyDeltaPackage(ReleasePackage basePackage, ReleasePackage deltaPackage, String outputFile)
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.UpdateManager.ApplyReleasesImpl.<createFullPackagesFromDeltas>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.UpdateManager.ApplyReleasesImpl.<ApplyReleases>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.UpdateManager.<ApplyReleases>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at . . .MoveNext()

I tried to find the root cause and this is what I came up with. **entryRegex** in ReleaseEntry.cs throws exception on line: 115

![image](https://user-images.githubusercontent.com/983708/48839307-1652b400-ed9c-11e8-8ed1-e37fa26d5463.png)

When I remove the spaces from the entry, it matches successfully. So what does this mean that it is not allowed to have files with spaces in the application? :)

**Comment by frederikolsen88** [comment] 2019-01-09 08:41
Have also had huge issues with this. For now, I've had to rename the afflicted files. See #1283. 

There's an open PR (#1401), but I don't think it has been reviewed yet.

**Comment by Thieum** [comment] 2019-05-03 14:16
@shiftkey duplicate of #713, this can be closed.

**Closed** 2019-05-04 21:05 UTC
