### ISSUE TITLE
Squirrel installer should give nicer message when run on XP

### ISSUE THREAD

**Issue by JohnThomson** [Squirrel/Squirrel.Windows#282] opened 2015-03-13 22:41 UTC
I understand that the installers Squirrel builds can't RUN on XP since you use .NET 4.5. But it would be nice to have a message better than what we get currently when someone downloads our installer on XP and executes it: "...BloomInstaller.3.1.57.Apha.exe is not a valid Win32 application". (This is our rename of your Setup.exe, not our own program).

Ideally we'd like to be able to configure it to display something like "Bloom 3.1 cannot run on Windows XP. You can still use Bloom 3.0 which is available at..."

**Comment by paulcbetts** [comment] 2015-03-13 22:45
@JohnThomson I definitely agree about the scenario, but the problem is to do that, I'd have to build it as a 32-bit app. If you build a Setup.exe as a 32-bit app, you are stuck in 32-bit filesystem and registry redirection, which means that Weird Things start happenning

**Comment by JohnThomson** [comment] 2015-03-13 23:01
I could live with that...the application we're trying to install is itself 32-bit. But of course you don't want to mess up clients that aren't.
I haven't yet investigated how much is actually done by setup.exe. My impression was that most of the registry stuff was done by Update.exe or the installed application itself. It's OK (I think) if update.exe won't run...I'd just like the little piece that is not .NET at all to be able to run on XP long enough to give a nice message.
My first look suggests it might help to just set Configuration Properties/General/Platform target to "Visual Studio 2013 - Windows XP (v120_xp)," but that may cause the exact problem you're talking about.
XP has 64-bit versions, IIRC, so it seems it ought to be possible to make a program that will run on 64-bit but give some sensible message on a 32-bit system...but I'm no expert in this area.
Thanks for thinking about it.

**Comment by paulcbetts** [comment] 2015-03-13 23:02
Wait. I may be full of shit. Anyways, I'll see what I can do about making this experience suck less

**Comment by JohnThomson** [comment] 2015-04-23 18:57
Did you get anywhere with this? I can only find two places that Setup accesses the registry (WriteRunOnceEntry() and IsDotNet45OrHigherInstalled()), and there are ways a 32-bit app can access the 64-bit registry. Are you interested in a patch if I can make one?

**Comment by paulcbetts** [comment] 2015-04-23 19:02
@JohnThomson Yeah, I would take a patch for that, at least to make a generic "This application isn't supported on Windows XP" message

**Comment by JohnThomson** [comment] 2015-04-23 19:27
I'll see what I can do. Initially I'm puzzled: it appears Setup.exe is already a 32-bit application (which makes me wonder how IsDotNet45OrHigherInstalled() is seeing the 64-bit registry entries). May just need to change the <PlatformToolset> to something XP will allow.

**Comment by JohnThomson** [comment] 2015-04-23 22:57
I think I have something working: https://github.com/Squirrel/Squirrel.Windows/pull/311.
Tested on XP/32 and 7/64

**Comment by UVLabs** [comment] 2015-10-10 06:31
Are you saying that squirrel installers will ONLY work on 64bit win7+ systems? no 32bit? Even though the actual app being installed is set to 32bit for compatibility sake?

**Comment by paulcbetts** [comment] 2015-10-10 15:10
No

**Comment by shiftkey** [comment] 2019-04-30 16:38
I'm going to close this out as it looks like #311 was merged, and I feel further investment in XP usage is very low priority...

**Closed by shiftkey** 2019-04-30 16:38 UTC
