### ISSUE TITLE
Pass arguments to Setup.exe

### ISSUE THREAD

**Issue by elmahdibenhadda** [Squirrel/Squirrel.Windows#839] opened 2016-09-29 09:39 UTC
Currently for installing an application, we need to run Setup.exe, and for launching the application with Update.exe, we need run the command :
`Update.exe --processStart MyExe.`

To pass arguments to the application : 
`Update.exe --processStart MyExe --process-start-args "arg1 arg2 arg3"`.

When we run the Setup.exe, it install the application and then execute Update.exe.

But how can we pass some arguments to the Setup.exe to install the application and then pass them (arguments) to Update.exe ?

Thanks!
Mehdi

**Comment by MrBlenny** [comment] 2016-11-03 07:06
I have the same question.

Specifically, how does one react the start-args?
I'm dealing with an electron (node/javascript) application. I was hoping the args would be available on node's `process.argv` but unfortunately not.

**Comment by MrBlenny** [comment] 2016-11-03 07:25
Ooops...
My mistake - the flag is visible in node's `process.argv` - not sure how I missed it...

**Comment by omichelsen** [comment] 2017-05-05 17:14
We have a need for exactly this, passing parameters to the `Setup.exe`, which will be passed on when the application is launched. However I haven't been able to make it work. Looking at `process.argv` only the `--squirrel-firstrun` arg is passed on by the installer.

@MrBlenny how did you make it work?

**Comment by Thieum** [comment] 2019-05-06 20:17
@shiftkey duplicate of #487 , this can be closed.

**Closed** 2019-05-06 23:57 UTC
