### ISSUE TITLE
Spaces in filename cause ReleaseEntry Regex to fail

### ISSUE THREAD

**Issue by frederikolsen88** [Squirrel/Squirrel.Windows#1283] opened 2018-04-11 06:37 UTC
I'm in a situation where Squirrel updating fails when iterating over one particular release entry

`E6651B768DB82076E7113086558548B4DA4F8F6F Artifact - BoxHeader - e7ee795c-99e1-4ecb-a72c-9a41461d8198.xml.shasum 8669`

using this Regex:

`^([0-9a-fA-F]{40})\s+(\S+)\s+(\d+)[\r]*$`

The culprit appears to be that `(\S+)` will only match non-whitespace characters. I've played a bit around with the Regex Tester at http://regexstorm.net/tester, and my suggestion would be to change the Regex to something similar to

`^([0-9a-fA-F]{40})\s+(.*).shasum[\s+](\d+)[\r]*$`

We don't really want to be forced to change the filenames or escape the spaces, so I'm interested in a solution where we can avoid that. Thanks in advance.

**Comment by frederikolsen88** [comment] 2018-05-18 16:11
@paulcbetts, would you accept a PR incorporating the suggestion above, or would there be caveats to that approach?

**Comment by paulcbetts** [comment] 2018-05-18 16:14
I'm confused, why is this file in your RELEASES file?

**Comment by frederikolsen88** [comment] 2018-05-18 16:50
Sorry, I realize now I was a bit unclear. 

`E6651B768DB82076E7113086558548B4DA4F8F6F Artifact - BoxHeader - e7ee795c-99e1-4ecb-a72c-9a41461d8198.xml.shasum 8669`

are the contents of the .shasum corresponding with the file in question in one of our delta packages. It is when trying to update using a delta package that our users get an "Invalid release entry" exception. If there are changes to apply to a file with spaces in the filename, that is.

So while the RELEASES file isn't in play, I guess the error message is worded like that is because you're using the same Regex to parse both .shasum files and the RELEASES file.

**Comment by JohnThomson** [comment] 2018-10-23 20:15
Having the same problem. Any time Squirrel decides to use a .diff (or .bsdiff) to represent the difference between old and new versions of a file, it generates a corresponding .shasum file along with the .diff. Here's an example of the shasum contents for one of our packages:

09E36653DEFCAFEDA55115AD81AC84E1B8D4A1FF Install Bloom Literacy Fonts.exe.shasum 12992

When applying the patch in DeltaPackage.applyDiffToFile, Squirrel calls VerifyPatchedFile(), which reads the .shasum file and passes the contents to ReleaseEntry.ParseReleaseEntry(), which fails to parse it because it can't match the spaces in the file name.

Squirrel then concludes that the patch is faulty, aborts the incremental update, and downloads the whole package, defeating the incremental update feature entirely.

I agree that Frederik's fix (or even just changing (\S+) to (.+) would fix the problem.

**Comment by JohnThomson** [comment] 2018-10-23 20:19
I suppose to be sure there is some filename present, and that if there are multiple spaces at the end none of them are put in the filename group, (\S.*shasum) would be better.

**Comment by cbenard** [comment] 2018-10-23 20:31
Wouldn't `(\w+)\s(.+)\s(\d+)` be much simpler to match the hash at the beginning and the length at the end?

**Comment by JohnThomson** [comment] 2018-10-23 20:40
(a) Paul's regex requires exactly 40 of the expected characters in the sha, a better validation.
(b) ^ and $ are needed to ensure it matches the whole file content for validation
(c) If there is more than one white-space character surrounding the file name, your version will include the extra white space in the filename, which is probably not good.
(d) Your version will match something with nothing but white space between the sha and the length, as long as there are at least three spaces
(e) A minimal change to fix the problem is usually wise if one is not fully familiar with a piece of code and all its purposes.

**Comment by cbenard** [comment] 2018-10-23 20:44
I assumed we were talking about matching per-line. You're right about the 3 spaces thing. I didn't even see the original regex which is a bit more complicated than it needs to be.

It does seem like a pretty easy fix, especially if you know each line begins with 40 upper-case hex characters for the hash and ends with a set of numbers for length and has a filename in the middle delineated with spaces before/after. I'm surprised it's still open. I was subscribed to it for some reason, but I can't even remember if I had the issue.

**Comment by cbenard** [comment] 2018-10-23 20:51
How about adding \S inside the filename group to ensure there's at least one non-space character and then allow multiple spaces before/after like this? Also, I made the filename match non-greedy so it won't match extra spaces between the filename and the hash/length.

`^([0-9a-fA-F]{40})\s+(\S.+?)\s+(\d+)\r*$`

I did a bunch of tests in The Regex Coach and it seems to work well, and it's very similar to the original.

**Comment by JohnThomson** [comment] 2018-10-23 20:59
It will probably work for much the same reason as mine: filenames that will really occur here will have at least two characters. However, in the case of a single-character file name followed by two spaces, it will include one of the spaces in the filename. (\S.*?) would be even better.
Both your version and mine also pass all the existing unit tests. But I think (\S.*?), which will allow a single character file name, is the best suggestion yet.

**Comment by cbenard** [comment] 2018-10-23 21:07
`\S.?` means one non-space and zero or one single character. You probably meant `.*?` or something, like a non-greedy zero-to-any length match.

This one allows single character filenames, at the expense of requiring a single space before/after the filename: `^([0-9a-fA-F]{40})\s(\S[\S ]*?)\s(\d+)\r*$`. It also stays closer to the original's definition of what a filename is (`\S`) plus spaces.

I don't have a dev env setup for this project, so I'm just trying to help with regex. :) I'll probably let this be my last comment on the matter.

**Comment by JohnThomson** [comment] 2018-10-23 21:11
No, I tried to write openparen-backslash-S-dot-star-questionmark-closeparen and markdown interpreted it as a request for italics. So I edited the comment, but unfortunately you saw the original. Sorry.

**Comment by cbenard** [comment] 2018-10-23 21:20
If you surround your "code" with backticks, you don't have to deal with the escapes. It'll also do a mono-space font with a gray background instead of italics like you're using.

Like this \`some \\code here\` makes it look like: `some \code here`

**Comment by cbenard** [comment] 2018-10-23 21:30
Yours has an error that makes it not work for single character filenames. You have an errant period inside the filename match after `(\S`. That requires at least 2 characters for a filename and the 2nd character can be anything, including whitespace like tabs/vertical tab/etc.

**Comment by JohnThomson** [comment] 2018-10-23 21:38
Bother. A careless mistake. The version I actually unit-tested is `^([0-9a-fA-F]{40})\s+(\S[\S ]+?)\s+(\d+)[\r]*$`

**Comment by cbenard** [comment] 2018-10-23 21:53
That one doesn't match single character filenames either. Your `[\S ]+` in the middle should be `*`, not `+`. If you use `+`, it requires at least one character, in addition to the `\S` which is another character to begin.

**Comment by cbenard** [comment] 2018-10-24 13:39
That one looks good. Consider it co-signed.

`^([0-9a-fA-F]{40})\s+(\S[\S ]*?)\s+(\d+)[\r]*$`

Now if we can only get @paulcbetts to look at this issue still open from April... :)

**Comment by cbenard** [comment] 2018-10-24 14:22
Got the PR ready for you @paulcbetts after @JohnThomson and I worked through the regex. I hope you're able to accept the PR.

**Comment by Thieum** [comment] 2019-05-03 14:15
@shiftkey duplicate of #713, this can be closed.

**Closed** 2019-05-04 21:05 UTC

**Comment by Keras-tunerwell-educated** [comment] 2025-10-17 21:57
> [@shiftkey](https://github.com/shiftkey) duplicate of [#713](https://github.com/Squirrel/Squirrel.Windows/issues/713), this can be closed.





https://image-rotation.github.io/qx6QhiaLw3RwHa/

**Comment by RareScrap** [comment] 2025-10-31 15:24
Still actual (#1898) in the latest release (v2.0.1)
