### ISSUE TITLE
UpdateManager.RestartApp() fails if main executable contains whitespace

### ISSUE THREAD

**Issue by schh** [Squirrel/Squirrel.Windows#1257] opened 2018-02-22 15:16 UTC
My main executable is named xxx xxx xxx.exe. RestartApp crops everything after the first space.
[SquirrelSetup.log](https://github.com/Squirrel/Squirrel.Windows/files/1748423/SquirrelSetup.log)

**Comment by SteveMavic** [comment] 2018-04-29 13:35
Have the same issue here

**Comment by Thieum** [comment] 2019-05-03 14:14
@shiftkey duplicate of #713, this can be closed.

**Closed** 2019-05-04 21:07 UTC

**Comment by jeremia** [comment] 2019-10-11 08:11
This is not a duplicate of [#713 ](https://github.com/Squirrel/Squirrel.Windows/issues/713).
[#713 ](https://github.com/Squirrel/Squirrel.Windows/issues/713) is about shortcuts not working.
This bug is in UpdateManager.RestartApp.
You only need to add quotes around the exe file when making the call to Update.exe.
See my pull request for fix.
