### ISSUE TITLE
Can we add spaces to the application folder?

### ISSUE THREAD

**Issue by SissiKonsta** [Squirrel/Squirrel.Windows#1162] opened 2017-09-29 08:36 UTC
Hello,

I'm using Squirrel for Windows version 1.7.5 and I'm trying to add spaces to the %AppData%\Local application folder name. For example, after Squirrel installation instead of %AppData%\Local\ **MyApplication** folder path I want to have %AppData%\Local\ **My Application**. First of all, is something like that possible? And if yes, how can this be done? Is there any parameter I can use? 

Thanks in advance.

Sissi Konsta

**Comment by Thieum** [comment] 2019-05-07 16:00
@shiftkey adding spaces where they shouldn't be, doesn't seem to be in scope. I would close as wontfix.

**Comment by gojanpaolo** [comment] 2019-05-09 23:45
@SissiKonsta I think this is not possible by design:
1. [Squirrel uses the `NuGet Package ID` for the install location](https://github.com/Squirrel/Squirrel.Windows/blob/master/docs/using/naming.md#local-install-location)
2. [Spaces are not allowed on `NuGet Package ID`](https://docs.microsoft.com/en-us/nuget/reference/nuspec#id).

**Comment by shiftkey** [comment] 2019-05-12 14:34
Closing this out as `wontfix` because of the limitations in the NuGet specification

**Closed by shiftkey** 2019-05-12 14:34 UTC
Labels: wontfix
