### ISSUE TITLE
Why doesn't SquirrelAwareApp.HandleEvents work with semver

### ISSUE THREAD

**Issue by shinpou** [Squirrel/Squirrel.Windows#1414] opened 2018-11-14 13:51 UTC
HandleEvents relies on System.Version - why is this?

Passing a semantic version, like 1.2.3-r123 causes an exception, whereas a version like this is exactly what we would have in our RELEASES-file.

**Comment by Thieum** [comment] 2019-05-02 14:32
duplicate of #688

**Closed** 2019-05-03 02:08 UTC
