### ISSUE TITLE
Install path options

### ISSUE THREAD

**Issue by StoltHD** [Squirrel/Squirrel.Windows#1518] opened 2019-07-27 08:19 UTC
You really should have feature for selecting the installation path for where to install the software.

Not every person want there software to be in the appdata folder on windows...

there are at least 3 path options that should be possible !
1. Application Path
2. Database Path (for those programs using databases)
3. Users File Store (not everyone use users \documents for this.

In addition you should provide options for adding path to software settings, plugin folders and template folders for those programs using this.

**Comment by eiymba** [comment] 2019-07-28 02:30
You could try [Inno Setup](https://github.com/jrsoftware/issrc) instead, because I think you're missing the point of what Squirrel is trying to accomplish. It's meant to be a hassle-free zero configuration experience for the user. `/AppData` is usually always guaranteed to exist by design of Windows. What you're proposing is the exact opposite. 😕

**Comment by anaisbetts** [comment] 2019-07-28 03:59
Sorry! Squirrel will never do any of these things. The goal of a Squirrel installer is to open the app as soon as possible, not to ask the user weird questions.

**Comment by StoltHD** [comment] 2019-07-30 14:08
Try install any exe file to appdata on a domain controlled computer where
security are high...

Sadly to many developers take shortcuts this days...

first thing I block is to install any executable files in appdata... Sadly
one of the software packages I really should have liked to use is using
squirrel...

And @Betts, to ask for install path, data path and storage path for a
software using any of those, are not weird, its the correct way to install
any software on windows...

søn. 28. jul. 2019 kl. 05:59 skrev Anaïs Betts <notifications@github.com>:

**Comment by eiymba** [comment] 2019-07-30 19:49
You have 3 solutions:

- Reconsider blocking installation to, and execution from, `%AppData%`. Scrutinise the certificate used to code sign instead.
- Fork the project and append the changes you desire yourself.
- Use an alternative installer.

> Sadly to many developers take shortcuts this days...

What's really sad is people acting self entitled and demanding features to open source software no longer maintained, instead of writing their own installer or forking from this one and modifying to fit their needs. 🙄

**Comment by StoltHD** [comment] 2019-07-31 08:24
Thanks for lettting me know that Squirrel is no longer maintained, then i can ask the developer to use something else, since their project is an ongoing project...

The sadesy thing are peiple like you, actually... That get buthurt when someone point out that something they do or have made, can be made better... And that they cant accept suggestions without going totally bananas...

But thanks for the informatuon , maybe you should add a note on github about the fact that this project is depricated... So developer move to other solutions for their ongoiing projects !



________________________________

**Comment by eiymba** [comment] 2019-07-31 08:53
The saddest thing is people like you, clueless about what you're doing and acting like you know you do.

You didn't know the state of the project even though it's a pinned issue.

You block execution from the AppData directory which it's no more assuring than executing from anywhere else, especially under user elevated control.

You haven't read about the software to see if it's even fit for your use case.

You then have the audacity to make demands for changes outside the scope of this project without even attempting to understand or propose a PR.

You disregard plausible and viable alternative solutions proposed by others.

I don't know what you're trying to make but it doesn't seem too promising if you don't know your tech stack and you're at the head of development. So if you want to criticise others for taking feedback negatively first take a look at yourself.

The least you could do is close the issue now.

**Comment by musmuris** [comment] 2019-07-31 19:07
@StoltHD  Many programs these days install to AppData (See Chrome, Slack - even Microsoft stuff like Teams these days (which also uses Squirrel under the hood).  Blocking exes from here is quite limiting.  

From your original list:

Application Path - if you mean Program Files then that needs Admin access and Squirrel explicitly wants to avoid that
Database Path (for those programs using databases) - not sure where this is?
Users File Store (not everyone use users \documents for this. - Documents or file store is for data files usually, not programs - but I can sort of understand it.

**Comment by anaisbetts** [comment] 2019-07-31 20:14
Alright! I think we've had enough discussion on this issue, given how many times it has been rehashed over and over and it's not going to change unless you've got a Time Travel machine and want to go back to 2012 and convince me to write it a different way.

If you're a developer wondering where to store different things, please comment and we'll be glad to explain The Squirrel Way to handle these things

**Comment by Locutus67** [comment] 2019-12-19 22:50
I really hope that those Discord guys using Sqirrel read that I had to uninstall their beloved software from my too small ssd (Windows partition) since there is no way to change the install path to my hdd. It's far from hassle-free when you have to find an alternative software instead of being able to use the software of your choice. Good bye Discord untill you change your policy.

**Comment by eiymba** [comment] 2019-12-19 23:21
@Locutus67 you can run Discord in browser at [discordapp.com](discordapp.com). The app actually loads this more-or-less. See if that's a viable alternative for you.

**Closed** 2019-12-20 19:13 UTC
