### ISSUE TITLE
Update.exe --uninstall only removes shortcut/registry entries for current user

### ISSUE THREAD

**Issue by esamelson** [Squirrel/Squirrel.Windows#1014] opened 2017-05-05 18:27 UTC
I'm trying to write a script to uninstall our app for every user on a machine (some of our customers have used the Machine-Wide installer).

Running as administrator, I'm able to loop through each account and run `%LOCALAPPDATA%\MyApp\Update.exe --uninstall`. This works great for the installation in the administrator account (the one I'm running this all from). But for every user aside from the administrator, the app directory is removed, but not the registry entries or shortcuts.

This is fixed if I go through the users one at a time and use `runas` to run the uninstall command, but this is infeasible for our customers. 

Is this the intended behavior of `Update.exe --uninstall`, or maybe just unavoidable on Windows? If so, is there any way to automate completely uninstalling from every user, which doesn't involve manually removing all of the shortcuts and registry entries?

**Comment by Thieum** [comment] 2019-05-06 18:59
@shiftkey duplicate of #390

**Closed** 2019-05-06 23:58 UTC
