### ISSUE TITLE
Multi-users installaltion

### ISSUE THREAD

**Issue by Naheulf** [Squirrel/Squirrel.Windows#1730] opened 2021-07-26 18:57 UTC
How to perform a multi-user installation ?

This installer extract/install the app in C:\Users\<User>\AppData\Roaming. On multi-user computer each user need to install it in it's own %appdata% folder. If there 3 users on the computer the software is downloaded 3 times, and also installed 3 times. (if everyone use the software). So it's downloaded and extracted and scanned by antivirus 2 times for nothing and takes 3 times more disk space for nothing. (With only Discord and Geogebra that mean 2Go downloaded/scanned and installed for noting)

**As end user**, how can I optimize all of that ? In both time, bandwidth and disk space ?

**Comment by anaisbetts** [comment] 2021-07-27 05:49
Dupe of #1608

**Closed by anaisbetts** 2021-07-27 05:49 UTC
