### ISSUE TITLE
Loading .gif window size is changed and it doesn't use application icon on task bar

### ISSUE THREAD

**Issue by turgayselvi** [Squirrel/Squirrel.Windows#1154] opened 2017-09-20 20:09 UTC
I noticed Loading.gif window size is changed after updating to newer version of squirrel.

Loading.gif window was bigger and it was showing application's icon on taskbar while I was using 1.5.2

Loading.gif window is smaller and it doesn't show right icon on taskbar after updating to latest version.

Is there any specific reason to make smaller? And icon issue?

I put screenshot for both version:

1.5.2 -> https://ibb.co/bAwaG5
1.7.8 -> https://ibb.co/eELP9Q

Thanks

**Comment by vadi2** [comment] 2017-11-09 09:49
Duplicate of https://github.com/Squirrel/Squirrel.Windows/issues/1124

**Comment by Thieum** [comment] 2019-05-03 03:14
@shiftkey considering it's a duplicate of #1124 , it should have been fixed by #1233 as well.

**Closed** 2019-05-03 13:05 UTC
